name: resecentrum
description: Journey planner for VÃ¤sttrafik

publish_to: 'none'

version: 2.2.0+17

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  app_links: ^6.1.1
  collection: ^1.18.0
  diacritic: ^0.1.3
  diffutil_sliverlist: ^0.5.1
  dio: ^5.1.1
  dotted_line: ^3.1.0
  flutter_custom_tabs: ^2.0.0
  maplibre_gl: ^0.20.0
  geolocator: ^12.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  html: ^0.15.1
  intl: ^0.19.0
  rxdart: ^0.28.0
  url_launcher: ^6.1.6
  uuid: ^4.1.0
  webview_flutter: ^4.0.7

dev_dependencies:
  build_runner: ^2.4.4
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/bus.png
    - assets/boat.png
    - assets/tram.png
    - assets/train.png
    - assets/railway.png
